name: Master
on:
  push:
    branches:
      - WrapInDocker
  schedule:
    - cron: '10 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Running
        run: |
          echo "Running!"